light_name: cls_light_myvqvae_double_adapt


optimizer:
  lr: 0.0005
  decay: 0.01

scheduler:
  warmup_step: 50


callbacks:
  monitor: val_loss 
  check_val_every_n_epoch: 2
  max_epochs: 200
  max_steps: -1
  save_top_k: 1
  monitor_mode: min
  patience: 2
  min_delta: 0

dataset:
  batch_size: 32
  num_workers: 4

kd:
  kd_lambda: 1.0
  temperature: 2.0

freeze_module: # cls_prediction_head
  - coarse_vq
  - fine_vq
  - decoder
  - reconstruct_decoder

  
